app/crud/urls.py
from django.urls import path

from crud.views import *

app_name = "crud"
urlpatterns = [
    # Categories
    path('statementcategories/list/', StatementCategoryListView.as_view(), name='statementcategory-list'),
    path('statementcategories/create/', StatementCategoryCreateView.as_view(), name='statementcategory-create'),
    # path('statementcategories/create-add-another/', StatementCategoryCreateAddAnotherView.as_view(),
    #      name='statementcategory-create-add-another'),
    path('statementcategories/update/<int:id>/', StatementCategoryUpdateView.as_view(),
         name='statementcategory-update'),
    path('statementcategories/delete/<int:id>/', StatementCategoryDeleteView.as_view(),
         name='statementcategory-delete'),

    # Statements
    path('statements/list/', StatementListView.as_view(), name='statement-list'),
    path('statements/create/', StatementCreateView.as_view(), name='statement-create'),
    # path('statements/create-add-another/', StatementCreateAddAnotherView.as_view(),
    #      name='statement-create-add-another'),
    path('statements/update/<int:id>/', StatementUpdateView.as_view(),
         name='statement-update'),
    path('statements/delete/<int:id>/', StatementDeleteView.as_view(),
         name='statement-delete'),
]

app/distribution/urls.py
from django.urls import path

from distribution.views import *

app_name = 'distribution'
urlpatterns = [
    path('settings/', Settings.as_view(), name='settings'),
    path('distribute/', Distribute.as_view(), name='distribute'),
]

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

urlpatterns = [
    path('', LoginView.as_view()),

    path('crud/', include('crud.urls', namespace='crud')),
    path('distribution/', include('distribution.urls', namespace='distribution')),

    path('admin/', admin.site.urls),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

app/templates/shared/index_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>МатПомощь</title>
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.css" %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/main.css" %}">


    <!-- Favicon settings -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top">
        <div class="container">
            <span class="navbar-brand">
                 <img src="{% static "images/maneki-neko.svg" %}" width="50" height="50" alt="">
            </span>
            <ul class="navbar-nav nav-pills mr-auto">
                <li class="nav-item {% if request.path == '/statements/list/' %} active {% endif %} ">
                    <a class="nav-link " href="{% url 'crud:statement-list' %}">Заявления</a>
                </li>
                <li class="nav-item {% if request.path == '/statementcategories/list/' %} active {% endif %}">
                    <a class="nav-link " href="{% url 'crud:statementcategory-list' %}">Категории</a>
                </li>
                <li class="nav-item {% if request.path == 'distribution/settings/' %} active {% endif %}">
                    <a href="{% url 'distribution:settings' %}" class="btn btn-outline-success">Распределение</a>
                </li>
            </ul>
            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Выйти</a>
        </div>
    </nav>
</header>
<main role="main" class="container">
    {% if messages %}
        <div class=" col-10 alert alert-success">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</main>
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.bundle.js" %}"></script>
{% block javascript %}
{% endblock %}

</body>
</html>