app/crud/urls.py
from django.urls import path

from crud.views import *

app_name = "crud"
urlpatterns = [
    # Categories
    path('statementcategories/list/', StatementCategoryListView.as_view(), name='statementcategory-list'),
    path('statementcategories/create/', StatementCategoryCreateView.as_view(), name='statementcategory-create'),
    # path('statementcategories/create-add-another/', StatementCategoryCreateAddAnotherView.as_view(),
    #      name='statementcategory-create-add-another'),
    path('statementcategories/update/<int:id>/', StatementCategoryUpdateView.as_view(),
         name='statementcategory-update'),
    path('statementcategories/delete/<int:id>/', StatementCategoryDeleteView.as_view(),
         name='statementcategory-delete'),

    # Statements
    path('statements/list/', StatementListView.as_view(), name='statement-list'),
    path('statements/create/', StatementCreateView.as_view(), name='statement-create'),
    # path('statements/create-add-another/', StatementCreateAddAnotherView.as_view(),
    #      name='statement-create-add-another'),
    path('statements/update/<int:id>/', StatementUpdateView.as_view(),
         name='statement-update'),
    path('statements/delete/<int:id>/', StatementDeleteView.as_view(),
         name='statement-delete'),
]

app/distribution/urls.py
from django.urls import path

from distribution.views import *

app_name = 'distribution'
urlpatterns = [
    path('settings/', Settings.as_view(), name='settings'),
    path('distribute/', Distribute.as_view(), name='distribute'),
]

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

urlpatterns = [
    path('', LoginView.as_view()),

    path('crud/', include('crud.urls', namespace='crud')),
    path('distribution/', include('distribution.urls', namespace='distribution')),

    path('admin/', admin.site.urls),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

app/distribution/models/payment.py
from django.db import models


class Payment(models.Model):
    amount = models.DecimalField('Сумма выплаты', max_digits=7, decimal_places=2)
    date = models.DateField('Дата выплаты')
    statement = models.OneToOneField('crud.statement', related_name='payment', verbose_name='Заявление', null=True,
                                     on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Выплата"
        verbose_name_plural = "Выплаты"

    def __str__(self):
        return f"{self.amount}р. от {self.date}"

app/distribution/forms/settings.py
from django import forms
from django.db.models import QuerySet
from django.utils import timezone

from crud.models import StatementCategory, Statement
from general.forms import *

MONTH_CHOICES = (
    (1, 'Январь'),
    (2, 'Февраль'),
    (3, 'Март'),
    (4, 'Апрель'),
    (5, 'Май'),
    (6, 'Июнь'),
    (7, 'Июль'),
    (8, 'Август'),
    (9, 'Сентябрь'),
    (10, 'Октябрь'),
    (11, 'Ноябрь'),
    (12, 'Декбрь'),
)


class SettingsValidationMixin:
    def clean(self):
        cleaned_data = super().clean()

        if any(cleaned_data.get(cat.id, False) for cat in StatementCategory.objects.all()):
            raise forms.ValidationError("Хотя бы одна категория должна быть выбрана")

        return cleaned_data


def settings_form_factory(categories: QuerySet = StatementCategory.objects.all()):
    today = timezone.now().date()

    fields = {
        'budget': forms.FloatField(required=True, label='Размер бюджета', min_value=1000),
        'distribution_year': forms.IntegerField(
            required=True,
            label='Год',
            initial=today.year,
        ),
        'distribution_month': forms.TypedChoiceField(
            required=True,
            label='Месяц',
            coerce=int,
            empty_value=1,
            choices=MONTH_CHOICES
        )
    }
    fields.update({
        str(category.id): forms.BooleanField(
            label=category,
            initial=True,
            required=False,
        ) for category in categories
    })

    result = type(
        'SettingsForm',
        (SettingsValidationMixin, BaseBoostrapFormMixin, forms.Form),
        fields
    )

    return result

app/distribution/views/distribute.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Q, Prefetch
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View

from crud.models import Statement, StatementCategory
from distribution.forms import settings_form_factory
from distribution.utils import get_criterion, normalize


class Distribute(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form_class = settings_form_factory()
        form = form_class(data=request.GET)
        if not form.is_valid():
            return render(request, 'distribution/settings.html', {'form': form})

        distribution_year = form.cleaned_data.pop('distribution_year')
        distribution_month = form.cleaned_data.pop('distribution_month')
        budget = form.cleaned_data.pop('budget')

        actual_statements = Statement.objects.filter(
            application_date__year=distribution_year,
            application_date__month=distribution_month
        )
        if not actual_statements.exists():
            return render(request, 'distribution/empty_statements.html')

        categories = StatementCategory.objects.filter(
            statements__application_date__year=distribution_year,
            statements__application_date__month=distribution_month
        ).annotate(
            statements_count=Count(
                'statements',
                filter=(
                        Q(statements__application_date__year=distribution_year) &
                        Q(statements__application_date__month=distribution_month)
                )
            )
        ).prefetch_related(
            Prefetch(
                'statements',
                queryset=Statement.objects.filter(application_date__year=distribution_year,
                                                  application_date__month=distribution_month)
            )
        )

        test_metrics = {
            category: {
                'count': normalize(
                    category.statements_count,
                    [category.statements_count for category in categories]
                ),
                'weight': normalize(
                    category.weight,
                    [category.weight for category in categories]
                )
            } for category in categories
        }

        estimated = {
            category: get_criterion(test_metrics[category])
            for category in categories
        }

        distribution = {
            category: budget * (estimated[category] / sum(estimated.values())) for category in categories
        }

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="distribution{}{}.csv"'.format(distribution_year,
                                                                                               distribution_month)

        writer = csv.writer(response)
        for category, category_budget in distribution.items():
            writer.writerows([
                [statement.student_data, category.title, "{:.2f}".format(category_budget / category.statements_count)]
                for statement in category.statements.all()
            ])

        return response

app/distribution/views/settings.py
from django.utils import timezone
from django.views.generic import FormView

from crud.models import StatementCategory
from distribution.forms import *


class Settings(FormView):
    template_name = "distribution/settings.html"

    def get_form_class(self):
        return settings_form_factory()

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'distribution_period': timezone.now().date(),
            'budget': 0,
        })
        initial.update({
            str(category.id): 'true' for category in StatementCategory.objects.all()
        })

        return initial

app/templates/distribution/empty_statements.html
{% extends "shared/index_layout.html" %}
{% block content %}
        <div class="row justify-content-center">
            <div class="col-6 shadow rounded p-3">
                <div class="row justify-content-center">
                    <p>Не найдено ни одного заявления за указанный период</p>
                    <a href="{% url 'crud:statement-create' %}" class="btn btn-primary">Добавить заявление</a>
                </div>

            </div>
        </div>
{% endblock %}
{% block javascript %}
{% endblock %}

app/templates/distribution/settings.html
{% extends "shared/index_layout.html" %}
{% block content %}
        <form action="{% url 'distribution:distribute' %}" method="get" class="col-10 shadow rounded p-3">
            <div class="col-10">
                {% if form.non_field_errors %}
                    <div class="col-auto">
                        {% for error in form.non_field_errors %}
                            <div class="row alert alert-danger">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in form %}
                    <div class="form-group row">
                        <label class="col-3 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="col-7 mb-3">
                            {{ field }}
                            {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row pl-4">
                <div class="col-auto">
                    <button class="btn btn-primary" id="saveButton" tabindex="1">Создать распределение</button>
                </div>
            </div>
        </form>
{% endblock %}
{% block javascript %}
{% endblock %}